version: "3"

services:
  mysql:
    image: arm64v8/mysql
    ports:
      - "3308:3306" # External port 3308 mapped to internal port 3306
    environment:
      MYSQL_ROOT_PASSWORD: Lebaoanh194470@
      MYSQL_DATABASE: graduation_database
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pLebaoanh194470@",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./GR_BE
    volumes:
      - ./GR_BE:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./GR_BE/config.env
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./GR_FE
    volumes:
      - ./GR_FE:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql-data:
